In [1]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
#range of numbers 
np.arange(9,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
print(arr.ndim)  #dimension
print(arr.shape) #shape
print(arr.size) #size
print(arr.dtype) #datatype

2
(2, 3)
6
int64


In [8]:
#type confesrtion
arr = np.array([1.2,2.5,3.7])
print(arr.dtype)
arr_int = arr.astype(int)
print(arr_int)
print(arr_int.dtype)

float64
[1 2 3]
int64


In [9]:
print(arr[1:5])
print(arr[::2])

[2.5 3.7]
[1.2 3.7]


In [10]:
#2d indexing
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(mat[1,2])
print(mat[1])

6
[4 5 6]


In [11]:
print(mat[:,1])

[2 5 8]


In [12]:
#coi=oping  array
a= np.array([1,2,3])
b = a.copy()
b[0] = 99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [13]:
a= np.array([1,2,3])
b = a
b[0] = 99
print(a)
print(b)

[99  2  3]
[99  2  3]


In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [15]:
print(a+10)
print(a*12)
print((a+b)*2)

[11 12 13]
[12 24 36]
[10 14 18]


In [16]:
#universal function
arr = np.array([1,4,9,16])
print(np.sqrt(arr))
print(arr.dtype)
print(np.log(arr))
print(np.exp(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))

[1. 2. 3. 4.]
int64
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
1
16
7.5
5.678908345800274


In [17]:
#boolean indexing 
arr = np.array([10,20,30,40,50])
print(arr[arr >25])

[30 40 50]


In [18]:
print(arr>25)

[False False  True  True  True]


In [19]:
#broadcasting Rule
#numpy automatically expanads smaller array
arr = np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [20]:
row = np.array([1,2,3])
print (mat + row)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [21]:
#matrix maltiplication
A= np.array([[1,2],
             [3,4]])
B = np.array([[5,6],
              [7,8]])
print(np.dot(A,B))  #dot product

[[19 22]
 [43 50]]


In [22]:
print(A.T)  #transpose

[[1 3]
 [2 4]]


In [23]:
#random  variable
np.random.rand(11) #only rand gives float value

array([0.63538359, 0.94095537, 0.13694469, 0.18214574, 0.69295431,
       0.07383307, 0.30589961, 0.11428964, 0.65515871, 0.17689826,
       0.20318036])

In [24]:
np.random.rand(11,22)

array([[0.89665879, 0.45323115, 0.78948653, 0.06409442, 0.65065457,
        0.14952315, 0.91624208, 0.38463018, 0.38240555, 0.39902139,
        0.89446554, 0.27858763, 0.36516007, 0.95661755, 0.39967555,
        0.9142368 , 0.05961376, 0.53545857, 0.9972971 , 0.75225672,
        0.15506551, 0.49668543],
       [0.78627956, 0.88231804, 0.914246  , 0.75599952, 0.34539836,
        0.09205368, 0.82247778, 0.61090937, 0.96650983, 0.54326743,
        0.14169918, 0.34433669, 0.71547112, 0.30215599, 0.56428494,
        0.54516914, 0.07292343, 0.95052678, 0.83561918, 0.35898459,
        0.0832153 , 0.40095167],
       [0.0638155 , 0.95924765, 0.33095816, 0.09664106, 0.15276354,
        0.32063732, 0.8965824 , 0.04210404, 0.50910079, 0.32695392,
        0.87425613, 0.56162037, 0.64396751, 0.11203283, 0.35386682,
        0.87962143, 0.48643705, 0.50990864, 0.72234381, 0.53485256,
        0.15318236, 0.92421871],
       [0.25142334, 0.53623337, 0.32450112, 0.80887216, 0.33299947,
        0.9253456

In [25]:
np.random.randint(1,100,10) #rand int for integer

array([28, 55, 48, 57, 52, 23, 86,  2,  4, 40], dtype=int32)

In [26]:
#reshapping
arr = np.arange(12)
print(arr.reshape(3,4))# purpose reshapeto covert one space to another shape]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
#QUUES : YOU ARE MANAGINNG THE ELECTRONICS SECTION STORE. you need to track the sales of *** 3 product  head ppones smartphone AND speakers over 4 da

In [28]:

#qestion 1
cp_arr = np.array([1500,3000,5000])
arr = np.array([[10,15,8,12],
                [5,7,8,12],
                [2,3,2,4]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(cp_arr)
print(cp_arr.shape)
print(cp_arr.ndim)



[[10 15  8 12]
 [ 5  7  8 12]
 [ 2  3  2  4]]
(3, 4)
2
[1500 3000 5000]
(3,)
1


In [29]:
# question 2
cp_arr = np.array([1500,3000,5000])
arr = np.array([[10,15,8,12],
                [5,7,8,12],
                [2,3,2,4]])

print(arr.shape)
print(arr.ndim)
print(cp_arr+2)
print(arr+2)

(3, 4)
2
[1502 3002 5002]
[[12 17 10 14]
 [ 7  9 10 14]
 [ 4  5  4  6]]


In [30]:
arr = ["mon", "tue","wed","thu",10,15,8,12,5,7,8,12,2,3,2,4]
arr2 = np.array([arr])
print= (arr2)