In [ ]:
#S1 #S2 #S3
import numpy as np
marks=np.array(([78,85,90],#Student 1
                [45,60,55],#Student 2
                [88,92,95],#Student 3
                [30,40,35],#Student 4
                [65,70,75]))#Student 5
marks

In [ ]:
print(marks.shape)
print(marks.size)
print(marks.dtype)

(5, 3)
15
int64


In [ ]:
#exact all marks of 2nd student
second = marks[1:2,:]
print(second)

[[45 60 55]]


In [ ]:
three = marks[0:,2:]
print(three)

[[90]
 [55]
 [95]
 [35]
 [75]]


In [ ]:
first = marks[0:1,1:2]
print(first)

[[85]]


In [ ]:
#calculate the avg marks of each student
avg_marks = np.mean(marks, axis=1)
print(avg_marks)

[84.33333333 53.33333333 91.66666667 35.         70.        ]


In [ ]:
#calculate the avg marks of each subject
avg_per_subject = np.mean(marks, axis=0)
print(avg_per_subject)


[61.2 69.4 70. ]


In [ ]:
#task c1 pass / fails mapping
pass_fail = np.where(marks >= 50, 'Pass', 'Fail')

In [ ]:
pass_s = avg_marks >= 50
print(pass_fail)

[['Pass' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']]


In [ ]:
fail_s = avg_marks < 50
print(fail_s)

[False False False  True False]


In [ ]:
#grade allocation
#use nested condition logic within numpy
grades = np.where(avg_marks >= 80, 'A',
                  np.where(avg_marks >= 70, 'B',
                           np.where(avg_marks >= 50, 'C',
                                    np.where(avg_marks < 50, 'D', 'F'))))

grades

array(['A', 'C', 'A', 'D', 'B'], dtype='<U1')

In [ ]:
grades = np.where(marks < 50, 0, np.where(marks < 70, 6, np.where(marks < 85 , 8, 10)))
grades


array([[ 8, 10, 10],
       [ 0,  6,  6],
       [10, 10, 10],
       [ 0,  0,  0],
       [ 6,  8,  8]])

In [ ]:
#create a backup of marks and change the first mark of the first student to 0. check if bsckup is changed or not

backup = marks.copy()
backup[0,0] = 0
print(backup)
print(marks)

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [ ]:
a uniersity monitor  elsectriciy ussge of 4 hostel  7 days(mon - sun)



#create a numpy array electricity using np.random.randit
#valuses between 120 and 650 

# create a numpy array electricity using np.random.randit
# valuses between 120 and 650 
# shape (4,7)
import as 

In [ ]:
import numpy as np
# Create a 2D array to represent electricity usage for 4 hostels over 7 days
electricity = np.random.randint(120,650, size=(4, 7))  # Random usage between 120 and 650 units
hostel = ['Hostel A', 'Hostel B', 'Hostel C', 'Hostel D']
print(electricity.shape)
print(electricity)
print(electricity.dtype)
print(electricity.size)
print(electricity.ndim)

(4, 7)
[[410 601 382 615 469 344 301]
 [579 413 542 504 251 173 352]
 [199 545 335 399 209 298 142]
 [255 142 397 198 486 506 270]]
int32
28
2


task b hotel wise martix 
find average electricity usage per hostel ,maximum usage per hostel per hostel and identify which hostel have the height average usage

In [ ]:
avg_electricity = np.average(electricity, axis=1)
print(avg_electricity)
max_electricity = np.max(electricity, axis=1)
print(max_electricity)


[446.         402.         303.85714286 322.        ]
[615 579 545 506]


TASK C = create new array penalized_usage such that 
value > 550 = multiplid by 1.20
all other values remmain unchanges


In [ ]:
print(np.where(electricity > 500,electricity*1.20,electricity))

[[410.  721.2 382.  738.  469.  344.  301. ]
 [694.8 413.  650.4 604.8 251.  173.  352. ]
 [199.  654.  335.  399.  209.  298.  142. ]
 [255.  142.  397.  198.  486.  607.2 270. ]]


comapre each hostel daily ussage wih its own weekly avearage . create a boolean matrix where:
true above hoatel average 
false below or equal to hostel avg
reques broad casting of a(4,) array acrrs a(4,7) arry


In [ ]:
weekly_avg = np.mean(electricity, axis=0)
print(weekly_avg)
compare = np.where(electricity > weekly_avg[])
print(compare)

[360.75 425.25 414.   429.   353.75 330.25 266.25]
(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 3, 3, 3]), array([0, 1, 3, 4, 5, 6, 0, 2, 3, 6, 1, 4, 5, 6]))


e1 
reshape the electricity data into SINGLE ROW Representing weekly usage(shape 1*28)
e2 
2 rows and 14 coloums


task f create ref_back

In [ ]:
ref_backup = electricity.copy()
ref_backup[2,3] = 1200
print(ref_backup)

[[ 410  601  382  615  469  344  301]
 [ 579  413  542  504  251  173  352]
 [ 199  545  335 1200  209  298  142]
 [ 255  142  397  198  486  506  270]]
