In [1]:
import numpy as np

daily_sales = np.array([
    [15, 18, 20, 22],   # Headphones (Mon–Thu)
    [10, 12, 14, 16],   # Smartwatches (Mon–Thu)
    [8,  9,  11, 13]    # Speakers (Mon–Thu)
])

print(daily_sales)


[[15 18 20 22]
 [10 12 14 16]
 [ 8  9 11 13]]


In [2]:
# 4 question
flattened_sales = daily_sales.reshape(12)
print(flattened_sales)


[15 18 20 22 10 12 14 16  8  9 11 13]


In [4]:
#4.2
discount_percentage = np.linspace(0, 100, 10)
print(discount_percentage)


[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [5]:
#5
#task 5.1
predicted_sales = np.random.randint(0, 21, size=(3, 4))
print(predicted_sales)


[[17  5  9 12]
 [14 19  5  5]
 [14  3 13  0]]


In [7]:
#5.2
random_values = np.random.rand(5)
print(random_values)


[0.31718325 0.34598196 0.82950447 0.88338815 0.41997704]


In [11]:
#5.3
sales_4_days = np.array([
    [15, 18, 20, 22, 25],   # Headphones
    [10, 12, 14, 16, 18],   # Smartwatches
    [8,  9,  11, 13, 15]    # Speakers
])



In [ ]:
#total item sold over 4 days
total_items_sold_4_days = np.sum(daily_sales)
print(total_items_sold_4_days)



168


In [ ]:
#total item sold for ech prodect
product_wise_total = np.sum(sales_5_days, axis=1)
print(product_wise_total)



[100  70  56]


In [20]:
# acces in numpy

arr = np.array([[1,2,3],
               [4,5,6]])
print(arr)
print(np.sum(arr, axis=0))
# print(sum(arr))

[[1 2 3]
 [4 5 6]]
[5 7 9]


In [ ]:
#where is numpy
result = np.where(arr < 0, 0 , arr)  #for arr <0 conditon , 0 for true , arr for false
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
#even and oodd
result = np.where(arr % 2 != 0, -1,arr)
print(result)

[[-1  2 -1]
 [ 4 -1  6]]


In [24]:
marks = np.array([45,36,77,89,99])
status = np.where(marks )

In [23]:
data = np.array([45,87,64,98,])
mean = np.mean(data)

In [25]:
# appliying where in 2d array
mat = np.array([
    10,67,85
            ],
[80,65,54])
result = np.array(mat >= 50, 1,0)
print(result)

TypeError: Field elements must be 2- or 3-tuples, got '80'