In [1]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
#range of numbers 
np.arange(9,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
print(arr.ndim)  #dimension
print(arr.shape) #shape
print(arr.size) #size
print(arr.dtype) #datatype

2
(2, 3)
6
int64


In [17]:
#type confesrtion
arr = np.array([1.2,2.5,3.7])
print(arr.dtype)
arr_int = arr.astype(int)
print(arr_int)
print(arr_int.dtype)

float64
[1 2 3]
int64


In [18]:
print(arr[1:5])
print(arr[::2])

[2.5 3.7]
[1.2 3.7]


In [21]:
#2d indexing
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(mat[1,2])
print(mat[1])

6
[4 5 6]


In [20]:
print(mat[:,1])

[2 5 8]


In [22]:
#coi=oping  array
a= np.array([1,2,3])
b = a.copy()
b[0] = 99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [26]:
a= np.array([1,2,3])
b = a
b[0] = 99
print(a)
print(b)

[99  2  3]
[99  2  3]


In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [30]:
print(a+10)
print(a*12)
print((a+b)*2)

[11 12 13]
[12 24 36]
[10 14 18]


In [34]:
#universal function
arr = np.array([1,4,9,16])
print(np.sqrt(arr))
print(arr.dtype)
print(np.log(arr))
print(np.exp(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))

[1. 2. 3. 4.]
int64
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
1
16
7.5
5.678908345800274


In [35]:
#boolean indexing 
arr = np.array([10,20,30,40,50])
print(arr[arr >25])

[30 40 50]


In [36]:
print(arr>25)

[False False  True  True  True]


In [38]:
#broadcasting Rule
#numpy automatically expanads smaller array
arr = np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [ ]:
mat 

SyntaxError: closing parenthesis ')' does not match opening parenthesis '{' on line 1 (1351265539.py, line 2)

In [ ]:
row = np.array([1,2,3])
print (mat + row)

In [ ]:
#matrix maltiplication
A= np.array([[1,2],
             [3,4]])
B = np.array([[5,6],
              [7,8]])
print(np.dot(A,B))  #dot product

[[19 22]
 [43 50]]


In [41]:
print(A.T)  #transpose

[[1 3]
 [2 4]]


In [ ]:
#random  variable
np.random.rand(11) #only rand gives float value

array([[0.26075645, 0.61222342, 0.98461688, 0.33275104, 0.82516747,
        0.14483899, 0.16483366, 0.25402422, 0.90083014, 0.04043495,
        0.58146282],
       [0.79538663, 0.05262856, 0.85422476, 0.81076602, 0.57252353,
        0.18320146, 0.46837298, 0.10413217, 0.90044769, 0.53588035,
        0.65624834],
       [0.52693297, 0.52515116, 0.38684969, 0.40362609, 0.35876796,
        0.75247433, 0.45172484, 0.71814523, 0.20652451, 0.13275193,
        0.20586183],
       [0.24126879, 0.55803546, 0.85314033, 0.54069145, 0.55471991,
        0.59872921, 0.49301727, 0.6279295 , 0.95090784, 0.29087563,
        0.38103327],
       [0.55972445, 0.04619608, 0.37616963, 0.14347514, 0.311567  ,
        0.09111091, 0.51497133, 0.64894952, 0.50707945, 0.61340336,
        0.6731001 ],
       [0.9420464 , 0.1046483 , 0.09132274, 0.73564694, 0.99663119,
        0.61605823, 0.47148749, 0.23685846, 0.09215167, 0.82733369,
        0.78907908],
       [0.632528  , 0.2980728 , 0.61582945, 0.00279128, 0.

In [ ]:
np.random.rand(11,22)

In [ ]:
np.random.randint(1,100,10) #rand int for integer

array([51, 69,  9, 37, 73,  5, 89,  1, 14, 84], dtype=int32)

In [51]:
#reshapping
arr = np.arange(12)
print(arr.reshape(3,4))# purpose reshapeto covert one space to another shape]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
#QUUES : YOU ARE MANAGINNG THE ELECTRONICS SECTION STORE. you need to track the sales of *** 3 product  head ppones smartphone AND speakers over 4 da

In [8]:

#qestion 1
cp_arr = np.array([1500,3000,5000])
arr = np.array([[10,15,8,12],
                [5,7,8,12],
                [2,3,2,4]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(cp_arr)
print(cp_arr.shape)
print(cp_arr.ndim)



[[10 15  8 12]
 [ 5  7  8 12]
 [ 2  3  2  4]]
(3, 4)
2
[1500 3000 5000]
(3,)
1


In [ ]:
# question 2
cp_arr = np.array([1500,3000,5000])
arr = np.array([[10,15,8,12],
                [5,7,8,12],
                [2,3,2,4]])

print(arr.shape)
print(arr.ndim)
print(cp_arr+2)
print(arr+2)

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [13]:
arr = ["mon", "tue","wed","thu",10,15,8,12,5,7,8,12,2,3,2,4]
arr2 = np.array([arr])
print= (arr2)

NameError: name 'sales' is not defined

In [15]:
discount_percentage = np.linspace(0, 100, 10)
print(discount_percentage)


TypeError: 'numpy.ndarray' object is not callable

In [3]:
import numpy as np