In [2]:
#S1 #S2 #S3
import numpy as np
marks=np.array(([78,85,90],#Student 1
                [45,60,55],#Student 2
                [88,92,95],#Student 3
                [30,40,35],#Student 4
                [65,70,75]))#Student 5
marks

array([[78, 85, 90],
       [45, 60, 55],
       [88, 92, 95],
       [30, 40, 35],
       [65, 70, 75]])

In [3]:
print(marks.shape)
print(marks.size)
print(marks.dtype)

(5, 3)
15
int64


In [4]:
#exact all marks of 2nd student
second = marks[1:2,:]
print(second)

[[45 60 55]]


In [5]:
three = marks[0:,2:]
print(three)

[[90]
 [55]
 [95]
 [35]
 [75]]


In [6]:
first = marks[0:1,1:2]
print(first)

[[85]]


In [7]:
#calculate the avg marks of each student
avg_marks = np.mean(marks, axis=1)
print(avg_marks)

[84.33333333 53.33333333 91.66666667 35.         70.        ]


In [8]:
#calculate the avg marks of each subject
avg_per_subject = np.mean(marks, axis=0)
print(avg_per_subject)


[61.2 69.4 70. ]


In [10]:
#task c1 pass / fails mapping
pass_fail = np.where(marks >= 50, 'Pass', 'Fail')

In [11]:
pass_s = avg_marks >= 50
print(pass_fail)

[['Pass' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']]


In [12]:
fail_s = avg_marks < 50
print(fail_s)

[False False False  True False]


In [ ]:
#grade allocation
#use nested condition logic within numpy
grades = np.where(avg_marks >= 80, 'A',
                  np.where(avg_marks >= 70, 'B',
                           np.where(avg_marks >= 50, 'C',
                                    np.where(avg_marks < 50, 'D', 'F'))))

grades

array(['A', 'C', 'A', 'D', 'B'], dtype='<U1')

In [26]:
grades = np.where(marks < 50, 0, np.where(marks < 70, 6, np.where(marks < 85 , 8, 10)))
grades


array([[ 8, 10, 10],
       [ 0,  6,  6],
       [10, 10, 10],
       [ 0,  0,  0],
       [ 6,  8,  8]])

In [ ]:
#create a backup of marks and change the first mark of the first student to 0. check if bsckup is changed or not

backup = marks.copy()
backup[0,0] = 0
print(backup)
print(marks)

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
